services:
  frontend:
    build:
      target: deps
    command: ['npm', 'run', 'dev', '--', '--host', '0.0.0.0', '--port', '5173']
    env_file:
      - .env
    environment:
      VITE_API_PROXY_TARGET: http://backend:3000
    ports:
      - '80:5173'
    volumes:
      - ./frontend:/app

  backend:
    build:
      target: deps
    command: ['npm', 'run', 'start:dev']
    volumes:
      - ./backend:/app

  worker:
    build:
      target: deps
    command: ['npm', 'run', 'start:worker:dev']
    volumes:
      - ./backend:/app

  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: unless-stopped
    networks:
      - internal
